---
- name: "Shell: Install required system packages"
  ansible.builtin.package:
    name:
      - bash
      - fish
      - tmux
    state: present

- name: "Shell: Change user shell to `fish`"
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/fish
