---
- name: "Shell: Install required system packages"
  ansible.builtin.package:
    name:
      - bash
      - fish
      - tmux
    state: present

- name: Change user shell to `fish`
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/fish
