---
- name: "Typewriter: Install `neovim`, `git`, `unzip`"
  become: true
  ansible.builtin.package:
    name:
      - neovim
      - git
      - unzip
      - cmake
      - gcc
      - ripgrep
    state: present

- name: "Typewriter: Check if old `neovim` config exists"
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.config/nvim"
  register: stat_neovim_config_result

- name: "Typewriter: Backup existing `neovim` configuration"
  ansible.builtin.copy:
    src:  "{{ ansible_env.HOME }}/.config/nvim/"
    dest:   "{{ ansible_env.HOME }}/.config/nvim.bak"
    mode: preserve
  when: "stat_neovim_config_result.stat.exists"

- name: "Typewriter: Clone `typewriter`"
  ansible.builtin.git:
    repo: https://github.com/DrOptix/typewriter.git
    dest: "{{ ansible_env.HOME }}/.config/nvim/"
    version: "v0.8.0"
    update: true
    force: true
