---
- name: Ensure tmux and dependencies are installed
  become: yes
  ansible.builtin.package:
    name:
      - tmux
      - xsel
      - fzf
    state: present

- name: Copy tmux config to user's home directory
  ansible.builtin.copy:
    src: ".config/tmux/"
    dest: "/home/{{ ansible_user_id }}/.config/tmux/"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: preserve

- name: Deploy tmux_session_manager to ~/.local/bin
  ansible.builtin.copy:
    src: ".local/bin/"
    dest: "/home/{{ ansible_user_id }}/.local/bin/"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: preserve

