---
- name: Upgrade system (RedHat)
  become: yes
  ansible.builtin.dnf:
    name: '*'
    state: latest
  when: ansible_os_family == "RedHat"

- name: Upgrade system (Debian)
  become: yes
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes
  when: ansible_os_family == "Debian"
