---
- name: Ensure personal projects location exists
  ansible.builtin.file:
    path: "/home/{{ ansible_user_id }}/Projects/personal/"
    state: directory
    mode: "0755"

- name: Clone personal projects
  environment:
    SSH_AUTH_SOCK: "{{ ssh_auth_sock }}"
    SSH_AGENT_PID: "{{ ssh_agent_pid }}"
  ansible.builtin.shell: |
    git clone-worktree {{ item.repo }} /home/{{ ansible_user_id }}/Projects/personal/{{ item.name }}/
  loop:
    - { name: "forger", repo: "git@github-droptix:DrOptix/forger.git" }
    - { name: "ghost_engine", repo: "git@github-droptix:DrOptix/GhostEngine.git" }
