---
- name: Include encrypted work projects list
  include_vars: work_projects.yml

- name: Ensure work projects location exists
  ansible.builtin.file:
    path: "/home/{{ ansible_user_id }}/Projects/work/"
    state: directory
    mode: "0755"

- name: Clone work projects
  environment:
    SSH_AUTH_SOCK: "{{ ssh_auth_sock }}"
    SSH_AGENT_PID: "{{ ssh_agent_pid }}"
  ansible.builtin.shell: |
    git clone-worktree "{{ item.repo }}" "/home/{{ ansible_user_id }}/Projects/work/{{ item.name }}/"
  loop: "{{ work_projects }}"
