---
- name: Ensure Neovim is installed
  become: yes
  ansible.builtin.package:
    name: 
      - neovim
      - git
    state: present

- name: Deploy neovim config to user's home
  ansible.builtin.copy:
    src: ".config/nvim/"
    dest: "/home/{{ ansible_user_id }}/.config/nvim/"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: preserve

- name: Install neovim plugins using Lazy.nvim
  ansible.builtin.command:
    cmd: nvim --headless +Lazy! sync +qa
