# Use the Ubuntu 24.04 base image
FROM ubuntu:24.04

# Upgrade the system and install sudo and ansible
RUN apt-get update \
    && apt-get --yes upgrade \
    && apt-get --yes install sudo ansible \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Create a user 'test' and add to sudoers with passwordless sudo
RUN useradd --create-home test \
    && echo 'test ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# Change container user
USER test

# Copy forger into the container
COPY . /home/test/.forger

# Run the playbook inside the container
RUN ANSIBLE_CONFIG=/home/test/.forger/ansible.cfg \
    ansible-playbook /home/test/.forger/playbooks/localhost.yml

