# Use the Ubuntu 24.04 base image
FROM ubuntu:24.04

# Upgrade the system and install sudo and ansible
RUN apt-get update \
    && apt-get --yes upgrade \
    && apt-get --yes install sudo ansible \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Create a user 'test' and add to sudoers with passwordless sudo
RUN useradd --create-home test \
    && echo 'test ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# Copy forger into the container
COPY --chown=test:test . /home/test/.forger

# Change container user
USER test


ENTRYPOINT ["/home/test/.forger/dockerfiles/entrypoint.sh"]
