# Use the Fedora 41 base image
FROM fedora:41

# Upgrade the system and install sudo
RUN dnf --assumeyes upgrade \
    && dnf --assumeyes install sudo \
    && dnf clean all

# Create a user 'test' and add to sudoers with passwordless sudo
RUN useradd --create-home test \
    && echo 'test ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# Clean up
RUN dnf clean all \
    && rm -rf /var/cache/dnf

