---
- name: Ensure eza is installed
  become: true
  ansible.builtin.package:
    name: eza
    state: present

- name: Read existing Fish config
  ansible.builtin.slurp:
    src: "/home/{{ ansible_user_id }}/.config/fish/config.fish"
  register: existing_config
  ignore_errors: true

- name: Read `eza` fish config
  ansible.builtin.slurp:
    src: "{{ playbook_dir }}/../roles/setup_eza/files/.config/fish/config.fish"
  register: new_config
  ignore_errors: true

- name: Merge Fish configurations
  ansible.builtin.template:
    src: merge_fish_config.j2
    dest: "/home/{{ ansible_user_id }}/.config/fish/config.fish"
    mode: "0644"
  when: existing_config is defined
