---
- name: Ensure fish shell is installed
  become: true
  ansible.builtin.package:
    name:
      - fish
    state: present

- name: Ensure fish shell is installed (ArchLinux)
  become: true
  ansible.builtin.package:
    name:
      - inetutils
    state: present
  when: ansible_distribution == "Archlinux"

- name: Make sure fish prompt dependencies are installed (RedHat)
  become: true
  ansible.builtin.package:
    name:
      - xclip
      - iproute
      - hostname
      - procps-ng
    state: present
  when: ansible_os_family == "RedHat"

- name: Make sure fish prompt dependencies are installed (Debian)
  become: true
  ansible.builtin.package:
    name:
      - xclip
      - iproute2
      - hostname
      - procps
    state: present
  when: ansible_os_family == "Debian"

- name: Change default shell to fish for test user
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/fish

- name: Deploy config to user's home directory
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: preserve
    backup: true
  loop:
    - { src: ".bashrc", dest: "/home/{{ ansible_user_id }}/.bashrc" }
    - { src: ".bash_profile", dest: "/home/{{ ansible_user_id }}/.bash_profile", }
    - { src: ".config/", dest: "/home/{{ ansible_user_id }}/.config/" }
