---
- name: Deploy .ssh directory to user's home
  ansible.builtin.copy:
    src: ".ssh/"
    dest: "/home/{{ ansible_user_id }}/.ssh"
    backup: yes

- name: Ensure ssh keys have 0600 permissions
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: 0600
  loop:
    - { path: "/home/{{ ansible_user_id }}/.ssh/github_droptix_ssh_ed25519" }
    - { path: "/home/{{ ansible_user_id }}/.ssh/github_askia_ssh_ed25519" }

- name: Ensure public ssh key have 0644 permission
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: 0644
  loop:
    - {
        path: "/home/{{ ansible_user_id }}/.ssh/github_droptix_ssh_ed25519.pub",
      }
    - { path: "/home/{{ ansible_user_id }}/.ssh/github_askia_ssh_ed25519.pub" }

- name: "Set authorized keys"
  authorized_key:
    user: "{{ ansible_user_id }}"
    state: present
    key: "{{ item.key }}"
  loop:
    - {
        key: "{{ lookup('file', '/home/{{ ansible_user_id }}/.ssh/github_droptix_ssh_ed25519.pub') }}",
      }
    - {
        key: "{{ lookup('file', '/home/{{ ansible_user_id }}/.ssh/github_askia_ssh_ed25519.pub') }}",
      }

- name: Create user systemd directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user_id }}/.config/systemd/user"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0755"

- name: Deploy user ssh-agent systemd service
  ansible.builtin.copy:
    src: ".config/systemd/user/ssh-agent.service"
    dest: "/home/{{ ansible_user_id }}/.config/systemd/user/"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0644"

- name: Enable user systemd service
  ansible.builtin.systemd:
    name: ssh-agent.service
    enabled: yes
    state: started
  become: yes
  become_user: "{{ ansible_user_id }}"
