---
- name: Localhost Workstation
  hosts: localhost
  pre_tasks:
    - name: System Upgrade
      ansible.builtin.import_tasks: ../tasks/sys_upgrade.yml
  tasks:
    - name: Install system packages
      ansible.builtin.import_tasks: ../tasks/sys_packages.yml

    - name: Configure `fish`
      ansible.builtin.import_tasks: ../tasks/fish.yml

    - name: Configure `neovim`
      ansible.builtin.import_tasks: ../tasks/typewriter.yml
