---
- name: Localhost Workstation
  hosts: localhost
  tasks:
    - name: System Upgrade
      ansible.builtin.import_tasks: ../tasks/sys_upgrade.yml

    - name: Vault Demo
      ansible.builtin.import_tasks: ../tasks/hello_vault.yml
